// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:recipe_app/data/models/hive/ingredient_detail_hive_model.dart';
import 'package:recipe_app/data/models/hive/meal_hive_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(IngredientDetailHiveModelAdapter());
    registerAdapter(MealHiveModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(IngredientDetailHiveModelAdapter());
    registerAdapter(MealHiveModelAdapter());
  }
}
